### ISSUE TITLE
Add support for “pipe” operator

### ISSUE THREAD

**Issue by lucaswerkmeister** [eclipse/ceylon.formatter#151]
AFAICT eclipse/ceylon#6615 isn’t quite settled yet, but it looks like some form of the operator will make it into the next release, so don’t forget to add support for it.

Looks like this:

```ceylon
shared void run() {
    "hello world how are you today, I'm doing great !!!! xxxxxyyy"
            |> String.size
            |> (Integer i) => Integer.format(i, 16) 
            |> String.uppercased 
            |> String.trimmed 
            |> print;
}
```

and should be formatted like that too, I think (one level of pre-indent, just like other binary operators).

**Comment by lucaswerkmeister** [comment]
Looks like the operator is settled now (final form: `|>`), see eclipse/ceylon@4c0288b45ae908ab91b00b25f889b0c380df30bd for spec.

**Comment by gavinking** [comment]
Pffffff. Hard, I think. You can't look at the token, or something?

**Comment by lucaswerkmeister** [comment]
I can try, but it’s almost certainly going to break as soon as you touch the desugaring code. And then I suppose I’ll also have to do the same thing in ceylon.ast, in both directions.

**Comment by gavinking** [comment]
Thanks @lucaswerkmeister. Sorry about the hackery.
